apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: nginx
    namespace: flux-system
  targetNamespace: default

